otel:
  exporter:
   otlp:
     endpoint: https://otlp.datadoghq.com

management:
  otlp:
    endpoint: https://otlp.datadoghq.com
    metrics:
      export:
        url: https://otlp.datadoghq.com/v1/metrics
        headers:
            dd-api-key: ${DD_API_KEY}
            dd-otel-metric-config: '{"resource_attributes_as_tags": true}'
        aggregation-temporality: delta
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: https://otlp.datadoghq.com/v1/traces
          headers:
              dd-api-key: ${DD_API_KEY}
    logging:
      export:
        otlp:
          endpoint: https://otlp.datadoghq.com/v1/logs
          headers:
              dd-api-key: ${DD_API_KEY}
